### ISSUE TITLE
rust中trait解决了继承的所有问题吗？

### ISSUE THREAD

**Issue by towry** [ifsheldon/RustWHY#1]
你文中提到：

> 继承有时候会共享过多东西（如用不上的属性、数据、方法等）。有时候子类并不需要父类的所有东西（人也是一样）。

> 首先，第一个理由就是高耦合。引申出来的问题就是，有时候子类并不需要父类的所有东西，但是继承一股脑都把父类的东西塞给子类了。大家都知道，没有免费的午餐，所以继承的东西也不是越多越好。例如，继承方法，万一子类需要写一个同名方法，但是有着不同的输入输出怎么办？有人说可以用重载，但是复杂度又增加了。

但是在 rust 中不是也有这样的问题吗？

```rs
trait Foo {
    fn call_me();
}

struct Bar;

impl Foo for Bar {
    fn call_me(name: &str) {
        println!("{}", name);
    }
}

fn main() {
    let b = Bar {};
    
    b.call_me("hello world");
}
```

报错信息:

```
Compiling playground v0.0.1 (/playground)
error[[E0050]](https://doc.rust-lang.org/stable/error-index.html#E0050): method `call_me` has 1 parameter but the declaration in trait `Foo::call_me` has 0
 [--> src/main.rs:8:22
](https://play.rust-lang.org/#)  |
2 |     fn call_me();
  |     ------------- trait requires 0 parameters
...
8 |     fn call_me(name: &str) {
  |                      ^^^^ expected 0 parameters, found 1
```

**Comment by ifsheldon** [comment]
首先，trait没有解决继承的所有问题，这个我在文章中说了，因为SuperTrait在某种程度上也可以变成继承的另一种形式。

其次，你举的例子其实是编译错误，编译器已经指出了问题，就是你定义的trait里的call_me是不需要参数的，但是你在impl Foo for Bar 的时候给了call_me一个参数，这个跟语言设计无关，只是你在写代码的时候的问题。

另外，你如果只是想要另外一个不同的call_me，你应该直接用impl而不是impl Trait for Struct。如果你想要自己的call_me同时还要这个trait，也可以，但是你就要写两个不同的impl块，并且调用的时候用全路径（这个在文中也写了）。

**Comment by towry** [comment]
> 另外，你如果只是想要另外一个不同的call_me，你应该直接用impl而不是impl Trait for Struct。如果你想要自己的call_me同时还要这个trait，也可以，但是你就要写两个不同的impl块，并且调用的时候用全路径（这个在文中也写了）。

谢谢解惑。
